apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
        - name: radarr
          image: lscr.io/linuxserver/radarr
          tag: latest
          port: 7878
          domains:
            - radarr.immaleix.casa
          mount:
            /mnt/local/configs/radarr: /config
            /mnt/nfs/homeflix-v2: /media
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          allow_from:
            - prowlarr
            - overseerr
            - bazarr
            - maintainerr
            - radarr-exporter
            - sizeondisk-exporter
            - discovarr
  template:
    metadata:
      name: 'homeflix-{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://stakater.github.io/stakater-charts
        chart: application
        targetRevision: 6.14.0
        helm:
          releaseName: '{{.name}}'
          values: |
            applicationName: '{{.name}}'
            additionalLabels:
              k8s-app: '{{.name}}'
            deployment:
              image:
                repository: {{.image}}
                tag: {{.tag}}
              ports:
                - containerPort: {{.port}}
                  name: http
                  protocol: TCP
              nodeSelector:
                kubernetes.io/hostname: worker-0
              containerSecurityContext:
                runAsNonRoot: false
                readOnlyRootFilesystem: false
              resources:
                {{- toYaml .resources | nindent 16 }}
              env:
                PUID:
                  value: "1000"
                PGID:
                  value: "1000"
                TZ:
                  value: "Europe/Madrid"
              volumes:
                {{- range $hostPath, $mountPath := .mount }}
                {{ $mountPath | replace "/" "" | lower }}:
                  hostPath:
                    path: {{ $hostPath }}
                {{- end }}
              volumeMounts:
                {{- range $hostPath, $mountPath := .mount }}
                {{ $mountPath | replace "/" "" | lower }}:
                  mountPath: {{ $mountPath }}
                {{- end }}
            service:
              enabled: true
              ports:
                - port: 80
                  name: http
                  protocol: TCP
                  targetPort: {{.port}}
            ingress:
              ingressClassName: traefik
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
                traefik.ingress.kubernetes.io/router.tls.certresolver: default
                gethomepage.dev/enabled: "true"
                gethomepage.dev/name: {{.name}}
                gethomepage.dev/icon: {{.name}}
              hosts:
                {{- range .domains }}
                - host: {{ . }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
                {{- end }}
              tls:
                - secretName: {{.name}}-tls
                  hosts:
                    {{- range .domains }}
                    - {{ . }}
                    {{- end }}
            networkPolicy:
              enabled: true
              ingress:
                - from:
                  {{- range .allow_from }}
                  - podSelector:
                      matchLabels:
                        k8s-app: {{ . }}
                  {{- end }}
      destination:
        name: homelab
        namespace: homeflix
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
